name: widget_quiz_generator
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Masayuki Ono <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  path: any
  http: any
  googleapis: any
  googleapis_auth: any

dev_dependencies:
  test: ^1.0.0
